version: '3.8'

services:
  app:
    build: .
    ports:
      - "6000:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=photodb
    ports:
      - "5432:5432"

volumes:
  postgres_data: 